---
docker_version: 1.10.3

# daemon options
docker_opts: --registry-mirror=http://fly2wind.m.alauda.cn

#
# registry
#
# A list of registries. e.g.
# docker_registries:
#   - host: docker.chatid.com
#     auth: path/to/ca.crt
docker_registries: []
